---
title: "Studieboek formaten"
description: |
  Zijn de digitale formaten PDF en EPUB als vervangers voor het papieren boek.
author:
  - name: Ben Welman
date: 09-20-2012
preview: ebooks.png
categories:
  - eboek
output:
  distill::distill_article:
    self_contained: false
draft: false
citation: false
---

# Wordt het papieren studieboek vervangen door het e-boek?

Een enquête in 2012 onder bezoekers van deze website leverde het volgende resultaat op.

*Hoe leest u een cursusboek het liefst?*

| **Antwoord** | **Aantal** | **Perc.** |
|--|--|--|
| In gedrukte vorm | 59 | 44% |
| Als pdf op pc/laptop | 57 | 43% |
| Als epub op tablet (iPad, ...) | 17 | 13% |
|--|--|--|
| Totaal | 133 | 100%|

## PDF

Het pdf formaat is het enige uitvoerformaat van Softwijs dat je kunt afdrukken, wat veel gebruikers ook nog steeds doen. Maar bij evaluaties van cursussen blijkt dat dit snel minder wordt. Veel cursisten geven er de voorkeur aan om het cursusboek als pdf op hun eigen laptop te lezen met het gratis programma Acrobat Reader. Dat heeft een aantal voordelen ten opzichte van een papieren boek.

-  Met het navigatievenster van Acrobat kun je snel door de inhoudsopgave bladeren en klikken op het gewenste onderdeel. De gewenste pagina verschijnt dan direct in het documentvenster.
-  Je kunt de zoekmogelijkheden van het programma gebruiken om snel een bepaald woord te vinden.
-  Je kunt de tekst vergroten en verkleinen. Een nadeel is dan wel dat de lay-out hetzelfde blijft en de tekst zich niet aanpast aan de afmetingen van het venster.
-  Je kunt gebruik maken van interne en externe hyperlinks die in de tekst voorkomen.

## EPUB

Het ePub formaat is bedoeld voor het lezen op een e-reader of tablet. Ook zijn er programma’s zoals het bekende Calibre om een ePub om een PC of laptop te lezen. Het scherm van een e-reader is eigenlijk te klein om er studieboeken op te lezen. Dat komt omdat in studieboeken vaak veel meer plaatjes en tekeningen voorkomen dan in romans. Het lezen van een studieboek op een tablet als de ipad is een stuk prettiger.

De hiervoor genoemde voordelen van een pdf heeft de ePub ook. Zo kun je van de inhoudsopgave gebruik maken en kun je de tekst doorzoeken. Bij het vergroten en verkleinen van de lettergrootte past de tekst zich aan het scherm aan. Een ePub heeft dan ook geen vast aantal pagina’s en het verwijzen naar een paginanummer heeft dan ook niet zoveel zin. Verder zijn de afbeeldingen vaak scherper dan in een pdf en kun je deze vergroten.

## Ontwikkelingen

Softwijs verwacht dat voor de cursusboeken de ePub steeds meer terrein zal winnen en de nieuwe standaard voor digitale cursusboeken zal worden en volgt de ontwikkelingen op dit terrein en voert deze in wanneer ze zinvol zijn. Het toekomstige digitale cursusboek zal steeds meer verrijkingen (geluid, video, animatie, hulp bij opgaven) bevatten en mogelijkheden tot interactie en samenwerking met medecursisten en docent.
