---
title: Power Pivot voor alle Windows Excel versies
description: |
  Beschikbaarheid van Power Pivot nu voor alle versies van Excel.
author:
  - name: Ben Welman
date: 10-19-2018
preview: preview.png
categories:
  - excel
  - powerpivot
output:
  distill::distill_article:
    self_contained: false
draft: false
citation: false
---

Toen Office 2016 voor het eerste beschikbaar kwam (september 2015) was het voor mij (en vele andere gebruikers) teleurstellend dat Power Pivot slechts in beperkte versies van Excel 2016 beschikbaar was. Gebruikers van Excel 2010 en Excel 2013 konden tot dan een gratis Power Pivot add-in installeren, maar met het uitkomen van Excel 2016 werd Power Pivot voor de zakelijke markt gepositioneerd. En het treurige was dat je dit pas ontdekte nadat je het product gekocht had, zoals ik met mijn Office 365 Home abonnement dat een volledig werkende versie van Excel zou bevatten.

Gelukkig is Microsoft dit voorjaar [van gedachten veranderd](https://www.myexcelonline.com/blog/power-pivot-is-now-available-in-all-versions-of-excel/) en wordt Power Pivot voor alle Windows versies van Excel beschikbaar gesteld. Het uitrollen hiervan is gestart via de maandelijkse updates vanaf mei 2018 (Build 9330 en daarna). Na het ontvangen van de update moet je deze COM-invoegtoepassing nog wel activeren via Invoegtoepassingen in Excel Opties. Daarna verschijnt Power Pivot op het lint.
