---
title: "Website bouwstenen (1)"
description: |
  Opsomming hulpprogramma's voor het maken van een statische website.
author:
  - name: Ben Welman
date: 09-09-2018
preview: preview.png
categories:
  - markdown
  - hugo
output:
  distill::distill_article:
    self_contained: false
draft: false
citation: false
---

Deze website is een zogenaamde statische website die door een generator uit een aantal brondocumenten is samengesteld. In dit eerste deel een korte opsomming en beschrijving van de gebruikte hulpmiddelen en werkwijze.

## Hulpmiddelen

1.  [Blogdown](https://bookdown.org/yihui/blogdown/), een R package voor het maken van statische websites met Rmarkdown.
2.  [RStudio](https://www.rstudio.com/), een geïntegreerde ontwikkelomgeving voor de taal **R**.
3.  [Hugo](https://gohugo.io/), een populaire open-source statische website generator.
4.  [Learn](https://themes.gohugo.io/hugo-theme-learn/), een thema voor Hugo
5.  [Git](https://git-scm.com/), een versiebeheer systeem.
6.  [GitHub](https://github.com/), een populaire hosting service voor **Git** repositories.
7.  [Netlify](https://www.netlify.com/), een platform voor het uitleveren van statische websites
8.  [Markdown](https://daringfireball.net/projects/markdown/) en [RMarkdown](https://rmarkdown.rstudio.com/) als opmaaktalen voor de brondocumenten
9.  [MathJax](https://www.mathjax.org/), een javascript engine voor wiskundige expressies in browsers.
10.  [Google Analytics](https://analytics.google.com), om het gebruik van de website te kunnen analyseren.


## Werkwijze

R, RStudio en Git waren al geïnstalleerd. Een GitHub en Google Analytics account was er ook al. In hoofdlijnen was de werkwijze

1.  Installatie van package Blogdown via RStudio.
2.  Een nieuw RStudio project gemaakt voor deze website gebaseeerd op *hugo-theme-docdock*.
3.  Van de projectmap een Git repository gemaakt.
4.  Diverse aanpassingen voor structuur en layout gemaakt.
5.  Nieuwe inhoud aangemaakt en een beperkt deel van de inhoud van de oude website geconverteerd en in een archiefmap geplaatst.
6.  Na uitgebreid testen de website op de server geplaatst.

*In een volgend artikel zal wat gedetailleerder op bepaalde onderdelen worden ingegaan.*

