---
title: "Latex werkomgeving"
description: |
  Hoe een werkomgeving voor Latex eruit kan zien.
author:
  - name: Ben Welman
date: 05-24-2020
preview: preview.png
categories:
  - latex
output:
  distill::distill_article:
    self_contained: false
draft: false
citation: false
---

LaTeX is een zeer krachtige opmaaktaal voor het maken van gestructureerde documenten. Het kan voor elk soort document gebruikt worden maar is uitermate geschikt voor documenten die wiskunde bevatten. Het is in de academische wereld van de wiskunde en natuurwetenschappen het meest gebruikte schrijfgereedschap. Het leent zich uitstekend voor het maken van scripties, artikelen, boeken, researchrapporten, presentaties, ... En LaTeX zelf is ook nog eens gratis.

Een LaTeX bestand is een plat tekstbestand met de extensie `.tex` en kun je in principe met Kladblok of Notepad maken. Er zijn echter betere alternatieven, zie verderop. Zo'n `.tex` bestand moet gecompileerd worden naar een `pdf` bestand. Daarvoor moet je over een LaTeX omgeving beschikken. Je kunt zo'n omgeving op een computer installeren, maar er zijn ook online mogelijkheden.

**Windows installatie**

LaTeX kun je op elk systeem installeren. Hier volgen alleen een paar korte instructies voor het opzetten van een LaTeX werkomgeving op een Windows computer.

1. Download een *basic* installatie van [MiKTeX](https://miktex.org/download) en voer de installatie uit.

MiKTeX is een TeX/LaTeX implementatie voor Windows en bevat de compiler. De installatie is eenvoudig en na afloop is er een grafische MiKTeX console beschikbaar waarmee je instellingen kunt regelen en updates kunt uitvoeren.

2. Download en installeer een editor (optioneel)

Met MiKTeX wordt ook de editor *TeXworks* meegeleverd. Dit is een goed bruikbare maar vrij kale editor. Mijn voorkeur gaat naar een meer geavanceerdere editor uit, zoals een van de volgende (gratis) prorogramma's:

+ [Texmaker](https://www.xm1math.net/texmaker/)
+ [TeXstudio](https://www.texstudio.org/)

**Online werkomgeving**

In plaats van te kiezen voor een lokale installatie op je computer kun je er ook voor kiezen om met een online TeX/LaTeX omgeving te werken. De meest bekende is **Overleaf**. Deze biedt drie smaken aan: Personal, Collaborator en Professional. Alleen de Personal omgeving is gratis en kent geen integratie met cloudomgevingen als dropbox en GitHub en ook zijn er mogelijkheden tot samenwerken met anderen.

De huidige online omgeving van Overleaf is gebouwd op basis van de **ShareLateX** editor, die daardoor niet meer als afzonderlijke online editor bestaat.

Overleaf kent verder een uitstekende [documentatie omgeving](https://www.overleaf.com/learn) met gidsen en tutorials over hoe je dingen in LaTeX voor elkaar kunt krijgen.

Gebruik Overleaf: ga naar https://www.overleaf.com/

Voordat je Overleaf kunt gebruiken moet je eerst een account aanmaken. Naast een eigen account kun je ook inloggen met bijvoorbeeld jouw Google of Twitter account.

De organisatie van documenten is in de vorm van projecten. Een project kan naast één of meerdere `.tex` bestanden ook referentiebestanden, afbeeldingen, stijlen, ... bevatten. De projectbestanden worden in jouw persoonlijke omgeving van Overleaf opgeslagen, maar kunnen ook gedownload worden naar de lokale computer. En omgekeerd kun je ook bestanden van de computer uploaden naar een project in Overleaf.
