---
title: "Latex in Markdown"
description: |
  De mogelijkheden om latex code op te nemen in platte Markdown.
author:
  - name: Ben Welman
date: 01-02-2020
categories:
  - latex
  - markdown
output:
  distill::distill_article:
    self_contained: false
draft: false
citation: false
---

Platte Markdown ondersteunt Latex niet of niet goed. Wanneer je veel wiskundige formules gebruikt kun je beter Rmarkdown gebruiken. Dan heb je ook het voordeel dat je formules kunt laten nummeren en referenties naar formules kunt maken.

Voor het geval dat je toch wiskunde in een markdown bestand wilt opnemen moet je gebruik maken van oplossingen die door [Yihui](https://yihui.org/en/2018/07/latex-math-markdown/) beschreven zijn. De door hem genoemde javascript functie wordt via de partial footer geladen.

> Voor de Latex syntax zie [Wikibook LaTeX/Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

**Inline stijl**

$sin^{2}x + \cos^{2}x = 1$ Met alleen enkele dollartekens: FOUT

`$sin^{2}x + \cos^{2}x = 1$` Met enkele dollartekens tussen backticks: GOED

\(sin^{2}x + \cos^{2}x = 1\) Tussen `\(` en `\)`: FOUT

`\(sin^{2}x + \cos^{2}x = 1\)` Tussen backticks en  `\(` en `\)`: GOED


Gebruik van enkele dollartekens wordt afgeraden en op termijn afgeschaft. Beter dus om de laatste oplossing te gebruiken.

**Display stijl**

Deze gaan goed, ook zonder de extra javascript functie.

*Wortelformule:*

$$
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
$$

*Sommatie*

$$
\sum_{i = 1}^{n}{(\bar{x} - x_i)^2}
$$

Echter er is ook Latex code die soms fout gaat, zoals de Wet van Gauss:

$$\oint_S {E_n dA = \frac{1}{{\varepsilon _0 }}} Q_{inside}$$

Maar nu hetzelfde tussen backticks:

`$$\oint_S {E_n dA = \frac{1}{{\varepsilon _0 }}} Q_{inside}$$`


En nog eentje (dubbele dollartekens tussen backticks):

`$$\begin{vmatrix}a & b\\
c & d
\end{vmatrix}=ad-bc$$`
