---
title: "Online studieboeken"
description: |
  De mogelijkheden om studieboeken online te publiceren.
author:
  - name: Ben Welman
date: 11-03-2019
preview: preview.png
categories:
  - eboek
  - dita
  - markdown
  - pdf
  - epub
output:
  distill::distill_article:
    self_contained: false
draft: false
citation: false
---

Hoe en ook hoe gemakkelijk je een boek online kunt zetten is niet zo simpel te beantwoorden. Ik kan eigenlijk alleen maar over mijn eigen ervaringen wat zeggen.

Belangrijke factoren

-  In welk formaat zijn de brondocumenten gemaakt en opgeslagen.
-  Wordt de inhoud regelmatig bijgewerkt en moeten deze wijzigingen steeds in de onlineversie doorgevoerd worden.
-  Zijn er meerdere auteurs die er aan werken.
-  Is het gratis toegankelijk of zit het achter een slot (registratie/inloggen)
-  Ondersteunt het auteursprogramma vormen van publiceren.
-  Moeten naast de onlineversie nog meerdere uitvoerformaten (pdf/latex, epub, ...) geproduceerd worden.

Gelet op de wijze waarop mijn boeken gemaakt en gepubliceerd worden heb ik op dit moment twee soorten systemen in gebruik, de ene gebaseerd op DITA/XML en de andere op Markdown.

## DITA/XML gebaseerd

De Excel en Access studieboeken zijn gebaseerd op het [DITA](https://nl.wikipedia.org/wiki/Darwin_Information_Typing_Architecture ) formaat, een bepaald XML formaat. Als auteursomgeving gebruik ik [Oxygen XML Editor](https://www.oxygenxml.com/), een commercieel programma welke ook een educational license heeft. Ik heb hier vele jaren mee gewerkt, maar doe er steeds minder mee (alleen beperkt onderhoud). De editor heeft mogelijkheden om vanuit dezelfde brondocumenten uitvoer te produceren in o.a. HTML, PDF en EPUB. De HTML uitvoer produceert een complete website. Deze HTML uitvoer wordt na elke wijziging geupload naar een repository op [Github](https://github.com/) en van daaruit vervolgens automatisch gepubliceerd op [Netlify](https://www.netlify.com/), een statische website generator. Zowel Github als Netlify zijn gratis te gebruiken.

*Wanneer je nooit met DITA dan wel XML gewerkt heb, kan ik je deze route niet aanbevelen. De drempel voor gebruik is nogal hoog. Verder is het werken met formules en wiskundige symbolen niet altijd even gemakkelijk.*

## (R)Markdown gebaseerd

Doordat ik me steeds meer voor data-analyse (en dus de bijbehorende statistiek) ben gaan interesseren ben ik een paar jaar geleden begonnen met de programmeertaal **R**. Rapportages van analyses en onderzoeken worden gemaakt in de eenvoudige opmaaktaal [Markdown](https://nl.wikipedia.org/wiki/Markdown) en een wat uitgebreider formaat [RMarkdown](https://rmarkdown.rstudio.com/. Markdown is eenvoudig te leren, is platte tekst en kun je met bijvoorbeeld Notepad maken. Er zijn ook wel gratis editors te vinden. Voor het werken met wiskundige symbolen werk je met Latex code, dat goed ondersteund wordt. Ook goed ondersteund wordt het werken met bibliografieën.

Een bijkomend voordeel van deze platte tekst formaten is dat je uitstekend met versiebeheer zoals [Git](https://git-scm.com/)) kunt werken, al dan niet in teamverband.

Als auteursomgeving voor R, Markdown en RMarkdown gebruik ik [RStudio](https://rstudio.com/) dat je gratis kunt downloaden en gebruiken. RStudio heeft ook vrij te gebruiken *packages* (een soort bibliotheken) uitgebracht waaronder **bookdown** en **blogdown** waarmee je respectievelijk een boek / website kunt produceren. Bookdown kent naast *latex/pdf* ook *html* gebaseerde uitvoer zoals *gitbook* en *tufte stijl*. Het gitbook formaat gebruik ik nu voor de nieuwe online boeken. Tufte stijl spreekt me nog meer aan, maar daar moet ik me nog wat meer in verdiepen.

De gitbook uitvoer kun je dan weer publiceren op een webserver. Je kunt bookdown en blogdown gebruiken zonder kennis van R programmeren. Indien wenselijk zijn workflowprocessen goed te automatiseren.

Natuurlijk moet je in het werken met markdown, rstudio, bookdown ook wel tijd investeren, maar veel minder dan in de XML wereld en ook de drempels zijn veel lager en software is gratis, vaak open source.

Voor wat voorbeelden van bookdown zie https://bookdown.org/home/archive/ Bij veel van deze boeken (niet allemaal) kom je op de online versie terecht wanneer je op het boek klikt. Erg fraai vind ik https://www-huber.embl.de/msmb/ op tufte-stijl gebaseerd.

## Andere formaten

Met een programma als Microsoft Word heb ik wel pdf's geproduceerd, maar nooit een online boek.

Om documenten te converteren van een aantal verschillende opmaakindelingen naar vele andere indelingen kun je het gratis [**Pandoc**](https://pandoc.org/) gebruiken. Bij de installatie van RStudio is Pandoc inbegrepen omdat rmarkdown hier gebruik van maakt.

